// <auto-generated />
using System;
using LystfiskerPortalen.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LystfiskerPortalen.Migrations
{
    [DbContext(typeof(LystFiskerContext))]
    partial class LystFiskerContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CommentReactions", b =>
                {
                    b.Property<int>("CommentId")
                        .HasColumnType("int");

                    b.Property<int>("ReactionId")
                        .HasColumnType("int");

                    b.HasKey("CommentId", "ReactionId");

                    b.HasIndex("ReactionId");

                    b.ToTable("CommentReactions", (string)null);
                });

            modelBuilder.Entity("LystfiskerPortalen.Models.Comment", b =>
                {
                    b.Property<int>("CommentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CommentId"));

                    b.Property<DateTime>("CommentTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("PostId")
                        .HasColumnType("int");

                    b.Property<string>("ProfileId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CommentId");

                    b.HasIndex("PostId");

                    b.HasIndex("ProfileId");

                    b.ToTable("Comments");

                    b.HasData(
                        new
                        {
                            CommentId = 1,
                            CommentTime = new DateTime(2025, 11, 23, 10, 35, 32, 316, DateTimeKind.Local).AddTicks(1253),
                            PostId = 3,
                            ProfileId = "user-guid-2",
                            Text = "Kæmpe tillykke Jens! Det er en drømmefisk."
                        },
                        new
                        {
                            CommentId = 2,
                            CommentTime = new DateTime(2025, 11, 23, 12, 35, 32, 316, DateTimeKind.Local).AddTicks(1255),
                            PostId = 3,
                            ProfileId = "user-guid-3",
                            Text = "Hvad tog den på? Flue eller spinner?"
                        },
                        new
                        {
                            CommentId = 3,
                            CommentTime = new DateTime(2025, 12, 1, 10, 35, 32, 316, DateTimeKind.Local).AddTicks(1257),
                            PostId = 4,
                            ProfileId = "user-guid-1",
                            Text = "Respekt for C&R! Flot fisk."
                        },
                        new
                        {
                            CommentId = 4,
                            CommentTime = new DateTime(2025, 11, 26, 10, 35, 32, 316, DateTimeKind.Local).AddTicks(1258),
                            PostId = 7,
                            ProfileId = "user-guid-2",
                            Text = "Jeg kommer helt sikkert!"
                        });
                });

            modelBuilder.Entity("LystfiskerPortalen.Models.Fish", b =>
                {
                    b.Property<int>("FishId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FishId"));

                    b.Property<int>("Length")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Weight")
                        .HasColumnType("float");

                    b.HasKey("FishId");

                    b.ToTable("Fishes");

                    b.HasData(
                        new
                        {
                            FishId = 1,
                            Length = 150,
                            Name = "Gedde",
                            Weight = 20.0
                        },
                        new
                        {
                            FishId = 2,
                            Length = 50,
                            Name = "Aborre",
                            Weight = 2.5
                        },
                        new
                        {
                            FishId = 3,
                            Length = 100,
                            Name = "Havørred",
                            Weight = 15.0
                        },
                        new
                        {
                            FishId = 4,
                            Length = 130,
                            Name = "Laks",
                            Weight = 25.0
                        },
                        new
                        {
                            FishId = 5,
                            Length = 120,
                            Name = "Torsk",
                            Weight = 30.0
                        });
                });

            modelBuilder.Entity("LystfiskerPortalen.Models.Location", b =>
                {
                    b.Property<int>("LocationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LocationId"));

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<double>("Longitude")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LocationId");

                    b.ToTable("Locations");

                    b.HasData(
                        new
                        {
                            LocationId = 1,
                            Latitude = 56.460500000000003,
                            Longitude = 9.9804999999999993,
                            Name = "Gudenåen"
                        },
                        new
                        {
                            LocationId = 2,
                            Latitude = 56.0,
                            Longitude = 12.380000000000001,
                            Name = "Esrum Sø"
                        },
                        new
                        {
                            LocationId = 3,
                            Latitude = 55.75,
                            Longitude = 12.666700000000001,
                            Name = "Øresund"
                        },
                        new
                        {
                            LocationId = 4,
                            Latitude = 56.366700000000002,
                            Longitude = 8.6166999999999998,
                            Name = "Storeåen"
                        });
                });

            modelBuilder.Entity("LystfiskerPortalen.Models.Post", b =>
                {
                    b.Property<int>("PostId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PostId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LocationId")
                        .HasColumnType("int");

                    b.Property<string>("Picture")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("PostTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("ProfileId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("PostId");

                    b.HasIndex("LocationId");

                    b.HasIndex("ProfileId");

                    b.ToTable("Posts");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("LystfiskerPortalen.Models.Profile", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("ProfilePicture")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "user-guid-1",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "995e5580-2eeb-4488-9fda-102520ca9bd4",
                            Email = "jens@lystfisker.dk",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "JENS@LYSTFISKER.DK",
                            NormalizedUserName = "JENS@LYSTFISKER.DK",
                            PasswordHash = "AQAAAAIAAYagAAAAENARgSVoBuMTAtuH1fi5fV/KsVMa44Qj2dXhMhijN80k5OBNb7lNNmrN3lIsgFMiLQ==",
                            PhoneNumberConfirmed = false,
                            ProfilePicture = "https://example.com/jens.jpg",
                            SecurityStamp = "7655deef-fbb6-4cde-9c8e-a20a5d89b071",
                            TwoFactorEnabled = false,
                            UserName = "jens@lystfisker.dk"
                        },
                        new
                        {
                            Id = "user-guid-2",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "9538670f-602a-476d-8a3f-9469634c3a42",
                            Email = "anne@lystfisker.dk",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "ANNE@LYSTFISKER.DK",
                            NormalizedUserName = "ANNE@LYSTFISKER.DK",
                            PasswordHash = "AQAAAAIAAYagAAAAEF5/jfxRZwG9qFHAaSnHChoAbR3xTl4YpKTQt2YIC7NGoSP5FYV6vXIn0/oaHwX4Zw==",
                            PhoneNumberConfirmed = false,
                            ProfilePicture = "https://example.com/anne.jpg",
                            SecurityStamp = "b206e42d-10fe-4138-be95-a56ee751876e",
                            TwoFactorEnabled = false,
                            UserName = "anne@lystfisker.dk"
                        },
                        new
                        {
                            Id = "user-guid-3",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "ede4db3a-91e2-4d26-be23-6d5404d1649c",
                            Email = "peter@lystfisker.dk",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "PETER@LYSTFISKER.DK",
                            NormalizedUserName = "PETER@LYSTFISKER.DK",
                            PasswordHash = "AQAAAAIAAYagAAAAEOaLPKG4U/Mz+lcCYEX/txQn3dlKTpufYFHGrXASQZHDXJ9Jl4DglZkkrsb/2fkgTA==",
                            PhoneNumberConfirmed = false,
                            ProfilePicture = "https://example.com/peter.jpg",
                            SecurityStamp = "acefa2e9-e1b5-4359-9d2b-4da752a9e916",
                            TwoFactorEnabled = false,
                            UserName = "peter@lystfisker.dk"
                        });
                });

            modelBuilder.Entity("LystfiskerPortalen.Models.Reaction", b =>
                {
                    b.Property<int>("ReactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReactionId"));

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PostId")
                        .HasColumnType("int");

                    b.Property<string>("ProfileId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ReactionId");

                    b.HasIndex("PostId");

                    b.HasIndex("ProfileId");

                    b.ToTable("Reactions");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("ProfileProfile", b =>
                {
                    b.Property<string>("FollowingId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProfileId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("FollowingId", "ProfileId");

                    b.HasIndex("ProfileId");

                    b.ToTable("ProfileFollowings", (string)null);
                });

            modelBuilder.Entity("LystfiskerPortalen.Models.Catch", b =>
                {
                    b.HasBaseType("LystfiskerPortalen.Models.Post");

                    b.Property<DateTime>("CatchTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("FishId")
                        .HasColumnType("int");

                    b.Property<string>("Lure")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Technique")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasIndex("FishId");

                    b.ToTable("Catches");

                    b.HasData(
                        new
                        {
                            PostId = 3,
                            Description = "Min første laks! Efter 3 dages forgæves fiskeri lykkedes det endelig.",
                            LocationId = 4,
                            Picture = "laks.jpg",
                            PostTime = new DateTime(2025, 11, 22, 10, 35, 32, 316, DateTimeKind.Local).AddTicks(1198),
                            ProfileId = "user-guid-1",
                            CatchTime = new DateTime(2025, 11, 22, 8, 35, 32, 316, DateTimeKind.Local).AddTicks(1199),
                            FishId = 4,
                            Lure = "Spinner",
                            Technique = "Spinnefiskeri"
                        },
                        new
                        {
                            PostId = 4,
                            Description = "Stor gedde i Esrum. Tog denne madamme på en stor wobler. Den fik friheden igen efter billedet.",
                            LocationId = 2,
                            Picture = "gedde.jpg",
                            PostTime = new DateTime(2025, 11, 30, 10, 35, 32, 316, DateTimeKind.Local).AddTicks(1202),
                            ProfileId = "user-guid-2",
                            CatchTime = new DateTime(2025, 11, 30, 9, 35, 32, 316, DateTimeKind.Local).AddTicks(1203),
                            FishId = 1,
                            Lure = "Wobler",
                            Technique = "Dørgning"
                        },
                        new
                        {
                            PostId = 5,
                            Description = "Aftentur efter torsk. Fik et par fine torsk med hjem til aftensmaden.",
                            LocationId = 3,
                            Picture = "torsk.jpg",
                            PostTime = new DateTime(2025, 12, 1, 22, 35, 32, 316, DateTimeKind.Local).AddTicks(1204),
                            ProfileId = "user-guid-3",
                            CatchTime = new DateTime(2025, 12, 1, 20, 35, 32, 316, DateTimeKind.Local).AddTicks(1205),
                            FishId = 5,
                            Lure = "Pirk",
                            Technique = "Pirkefiskeri"
                        });
                });

            modelBuilder.Entity("LystfiskerPortalen.Models.Event", b =>
                {
                    b.HasBaseType("LystfiskerPortalen.Models.Post");

                    b.Property<DateTime>("EventTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("Events");

                    b.HasData(
                        new
                        {
                            PostId = 6,
                            Description = "Kom og vær med til årets store geddekonkurrence på Esrum Sø. Fine præmier!",
                            LocationId = 2,
                            Picture = "",
                            PostTime = new DateTime(2025, 11, 2, 10, 35, 32, 316, DateTimeKind.Local).AddTicks(1222),
                            ProfileId = "user-guid-3",
                            EventTime = new DateTime(2026, 2, 2, 10, 35, 32, 316, DateTimeKind.Local).AddTicks(1225),
                            Title = "Esrum Open 2025"
                        },
                        new
                        {
                            PostId = 7,
                            Description = "Vi mødes ved broen og samler affald. Foreningen giver kaffe og kage bagefter.",
                            LocationId = 1,
                            Picture = "",
                            PostTime = new DateTime(2025, 11, 25, 10, 35, 32, 316, DateTimeKind.Local).AddTicks(1230),
                            ProfileId = "user-guid-1",
                            EventTime = new DateTime(2025, 12, 16, 10, 35, 32, 316, DateTimeKind.Local).AddTicks(1231),
                            Title = "Fælles oprydning ved Gudenåen"
                        });
                });

            modelBuilder.Entity("LystfiskerPortalen.Models.GeneralPost", b =>
                {
                    b.HasBaseType("LystfiskerPortalen.Models.Post");

                    b.Property<bool>("IsQuestion")
                        .HasColumnType("bit");

                    b.ToTable("GeneralPosts");

                    b.HasData(
                        new
                        {
                            PostId = 1,
                            Description = "Sæsonstart ved Gudenåen! Vandstanden ser perfekt ud, og vejret er med os. Knæk og bræk til alle derude.",
                            LocationId = 1,
                            Picture = "",
                            PostTime = new DateTime(2025, 11, 18, 10, 35, 32, 316, DateTimeKind.Local).AddTicks(1119),
                            ProfileId = "user-guid-1",
                            IsQuestion = false
                        },
                        new
                        {
                            PostId = 2,
                            Description = "Er der nogen der har erfaring med det nye Shimano hjul? Overvejer at købe det til kystfiskeri.",
                            LocationId = 3,
                            Picture = "",
                            PostTime = new DateTime(2025, 11, 27, 10, 35, 32, 316, DateTimeKind.Local).AddTicks(1168),
                            ProfileId = "user-guid-3",
                            IsQuestion = true
                        });
                });

            modelBuilder.Entity("CommentReactions", b =>
                {
                    b.HasOne("LystfiskerPortalen.Models.Comment", null)
                        .WithMany()
                        .HasForeignKey("CommentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LystfiskerPortalen.Models.Reaction", null)
                        .WithMany()
                        .HasForeignKey("ReactionId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("LystfiskerPortalen.Models.Comment", b =>
                {
                    b.HasOne("LystfiskerPortalen.Models.Post", "Post")
                        .WithMany("Comments")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("LystfiskerPortalen.Models.Profile", "Profile")
                        .WithMany("Comments")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Post");

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("LystfiskerPortalen.Models.Post", b =>
                {
                    b.HasOne("LystfiskerPortalen.Models.Location", "Location")
                        .WithMany("Posts")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LystfiskerPortalen.Models.Profile", "Profile")
                        .WithMany("Posts")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Location");

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("LystfiskerPortalen.Models.Reaction", b =>
                {
                    b.HasOne("LystfiskerPortalen.Models.Post", "Post")
                        .WithMany("Reactions")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("LystfiskerPortalen.Models.Profile", "Profile")
                        .WithMany("Reactions")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Post");

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("LystfiskerPortalen.Models.Profile", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("LystfiskerPortalen.Models.Profile", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LystfiskerPortalen.Models.Profile", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("LystfiskerPortalen.Models.Profile", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ProfileProfile", b =>
                {
                    b.HasOne("LystfiskerPortalen.Models.Profile", null)
                        .WithMany()
                        .HasForeignKey("FollowingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LystfiskerPortalen.Models.Profile", null)
                        .WithMany()
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LystfiskerPortalen.Models.Catch", b =>
                {
                    b.HasOne("LystfiskerPortalen.Models.Fish", "Fish")
                        .WithMany()
                        .HasForeignKey("FishId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LystfiskerPortalen.Models.Post", null)
                        .WithOne()
                        .HasForeignKey("LystfiskerPortalen.Models.Catch", "PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Fish");
                });

            modelBuilder.Entity("LystfiskerPortalen.Models.Event", b =>
                {
                    b.HasOne("LystfiskerPortalen.Models.Post", null)
                        .WithOne()
                        .HasForeignKey("LystfiskerPortalen.Models.Event", "PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LystfiskerPortalen.Models.GeneralPost", b =>
                {
                    b.HasOne("LystfiskerPortalen.Models.Post", null)
                        .WithOne()
                        .HasForeignKey("LystfiskerPortalen.Models.GeneralPost", "PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LystfiskerPortalen.Models.Location", b =>
                {
                    b.Navigation("Posts");
                });

            modelBuilder.Entity("LystfiskerPortalen.Models.Post", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Reactions");
                });

            modelBuilder.Entity("LystfiskerPortalen.Models.Profile", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Posts");

                    b.Navigation("Reactions");
                });
#pragma warning restore 612, 618
        }
    }
}
